name: Terragrunt CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      changes_detected: ${{ steps.set-matrix.outputs.changes_detected }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Detect changed directories
      id: set-matrix
      run: |
        echo "Starting change detection process..."
        
        echo "Making detect_changes.sh executable..."
        chmod +x ./detect_changes.sh
        
        echo "Executing detect_changes.sh..."
        DIRS=$(./detect_changes.sh 2>&1)
        RESULT=$?
        
        echo "Debug output from detect_changes.sh:"
        echo "$DIRS" | grep -v '^['
        
        echo "JSON output from detect_changes.sh:"
        JSON_OUTPUT=$(echo "$DIRS" | grep '^[')
        echo "$JSON_OUTPUT"
        
        echo "Setting matrix output..."
        echo "matrix=$JSON_OUTPUT" >> $GITHUB_OUTPUT
        
        echo "Determining if changes were detected..."
        if [ "$JSON_OUTPUT" == "[]" ]; then
          echo "No changes detected."
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in the following directories:"
          echo "$JSON_OUTPUT" | jq -r '.[]'
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        fi
        
        echo "Change detection process completed."
        exit $RESULT
    - name: Debug output
      run: |
        echo "Matrix output: ${{ steps.set-matrix.outputs.matrix }}"
        echo "Changes detected: ${{ steps.set-matrix.outputs.changes_detected }}"

  # ... rest of the workflow remains the same