name: Terraform fmt-and-commit

on:
  workflow_dispatch:

env:
  TERRAFORM_VERSION: 1.9.8
  TERRAGRUNT_VERSION: 0.68.4
  TFLINT_VERSION: "latest"

concurrency:
  group: terragrunt-ci
  cancel-in-progress: false

jobs:
  terraform-fmt-and-commit:
    name: "terragrunt-fmt-and-commit"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          wget -q -O /usr/local/bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64"
          chmod +x /usr/local/bin/terragrunt
          terragrunt -v

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Terraform fmt (For .tf files)
        run: terraform fmt -recursive
  
      - name: Terragrunt hclfmt (For .hcl files)
        run: terragrunt hclfmt

      - name: TFLint Recursive
        run: tflint --recursive --fix --color

      - name: Git Status
        run: git status

      - name: Commit changes
        if: ${{ github.ref_name != 'main' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Format Terraform and Terragrunt files'
          author_name: 'GitHub Actions[bot]'
          author_email: 'actions@github.com[noreply]'